### ISSUE TITLE
PrimeNG Not Working!

### ISSUE THREAD

**Issue by noro55** [coreui/coreui-free-angular-admin-template#89] opened 2018-06-04 13:51 UTC
Fixed it!

**Comment by xidedix** [comment] 2018-06-22 12:15
I'm closing this since the issue is no longer active. Please comment and/or reopen if you feel the issue has not been resolved.

**Closed by xidedix** 2018-06-22 12:15 UTC

**Comment by Imran-github** [comment] 2020-07-20 23:03
> Fixed it!

How was it fixed?
