### ISSUE TITLE
[Angular 5] Error: Cannot find module '@angular-devkit/core'

### ISSUE THREAD

**Issue by Deilan** [coreui/coreui-free-angular-admin-template#54] opened 2018-01-27 09:35 UTC
**Node.js**: `8.9.4 x64`
**npm**: `5.6.0`

Repro steps:
1. `git clone https://github.com/mrholek/CoreUI-Angular.git`
2. `cd CoreUI-Angular/Angular5_CLI_Starter`
3. `npm install`
4. `npm start`

Result:
```
module.js:540
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (module.js:538:15)
    at Function.Module._load (module.js:468:25)
    at Module.require (module.js:587:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Dev\CoreUI-Angular\Angular5_CLI_Starter\node_modules\@angular-devkit\schematics\src\tree\virtual.js:10:16)
    at Module._compile (module.js:643:30)
    at Object.Module._extensions..js (module.js:654:10)
    at Module.load (module.js:556:32)
    at tryModuleLoad (module.js:499:12)
    at Function.Module._load (module.js:491:3)
```

**Comment by tanwarsatya** [comment] 2018-01-29 00:52
yes I confirm this is an issue

**Comment by xidedix** [comment] 2018-01-29 10:52
cannot reproduce
`@angular-devkit` is required by `@angular/cli` as dependency
maybe something went wrong with `npm install` 
- what's your version of `node` and `npm`?
- remove `node_modules` directory and `package-lock.json` file, retry `npm install`
- sometimes npm's cache gets confused, reset it with `npm cache clean`

please let us know if this helps

**Comment by immad-hamid** [comment] 2018-01-30 17:20
I faced the same issue Today. This is how I fixed it:

1: Updated Angular Cli Globally by running:
npm update -g @angular/cli

2: Remove node_modules folder from the project and then check the Angular Cli version by hitting ng -v like this:
![image](https://user-images.githubusercontent.com/10588714/35580490-02f6c5d2-060b-11e8-9a6c-2adaf9704ae0.png)

3: Check your project's package.json file,  if the version you checked earlier are same then goto your cmd and run npm install if not then change the @angular/cli version to the version you checked and then run npm install
![image](https://user-images.githubusercontent.com/10588714/35580589-46a26cb4-060b-11e8-8b79-01d61327f69b.png)

IT SHOULD START WORKING NOW...

Note: The above solution is valid and if it doesn't work then you can follow my steps or you can directly use steps mentioned by me. Its a permanent fix.

**Comment by ramachandrann** [comment] 2018-02-02 20:19
worked for me!

**Comment by parthmakadiya12** [comment] 2018-02-04 14:31
Also get the same error ..
**Thank You everyone for Help**
![sss](https://user-images.githubusercontent.com/10697769/35778533-74f6ceb0-09e5-11e8-83c9-dc8293525c75.PNG)

1.Just Updated the cli version globally. (1.6.7)
`npm install --save-dev @angular/cli@latest -g`
2.Delete Node_Module
3.`npm install`
4.change package.json ->cli version to 1.6.7
5.check version `ng-v`
6. Serve `ng s`

**Comment by immad-hamid** [comment] 2018-02-04 15:34
@parthmakadiya12 
You need to update your cli globally what you have done changed your package in your project --save-dev update's your project package. Now the problem is that globally you are running old package and in your project you are running updated packages.

Just run `npm update -g` and things would get fine. Thanks

**Comment by SebastianOpiyo** [comment] 2018-02-06 19:38
It worked fine for me thanks @immad-hamid

**Comment by jogaian282** [comment] 2018-02-22 17:08
Install npm i @angular-devkit/core --save-dev as development dependency and try

**Comment by SebastianOpiyo** [comment] 2018-02-23 06:12
thanks.

**Comment by immad-hamid** [comment] 2018-02-23 16:45
@deilan
I believe you should close this issue...

**Comment by Pawan-git** [comment] 2018-02-23 19:41
I just do the following:
1. Updated "@angular/cli": "1.5.4" to "@angular/cli": "^1.5.4" in "devDependencies"
and then run the command:
npm update
and it gets fixed for me

**Comment by sabbarbutt** [comment] 2018-03-26 15:18
I struggled with the same problem. My project was generated using the v 1.6.0 of angular-cli.

npm update -g @angular/cli
editing my package.json changing the line
"@angular/cli": "1.6.0",
to
"@angular/cli": "^1.6.0",
npm update
did the trick.

**Comment by xidedix** [comment] 2018-08-28 13:51
I'm closing this since it appears to be inactive or answered above. Please comment and/or reopen if you feel the issue has not been resolved.

**Closed by xidedix** 2018-08-28 13:51 UTC

**Comment by sashikiran52** [comment] 2019-03-11 11:06
I installed angular (latest version 7.3.5) in windows 10 with command npm install -g @angular/cli , facing the same issue I followed the above steps but  not fixed, could you help on this (this is fresh installation not created projects)

internal/modules/cjs/loader.js:584
    throw err;
    ^

Error: Cannot find module '@angular-devkit/core'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (C:\Users\kiran.vadlamuri\AppData\Roaming\npm\node_modules\@angular\cli\lib\init.js:13:16)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

**Comment by xidedix** [comment] 2019-03-18 12:47
hi @sashikiran52 
please try `npm i -D @angular-devkit/core` in the project folder

**Comment by sashikiran52** [comment] 2019-03-29 07:42
> hi @sashikiran52
> please try `npm i -D @angular-devkit/core` in the project folder
Hi @xidedix,
Thank you, but It don't work.

I found the solution, I uninstalled the Blue coat web agent in my laptop then I did angular installation got successful.
